sonar.projectKey=poster
sonar.projectName=Poster

sonar.sources=backend,frontend/src

sonar.exclusions=backend/tests/**,frontend/test/**,frontend/coverage/**,**/node_modules/**,**/__pycache__/**,**/.venv/**,**/venv/**,**/dist/**,**/build/**

sonar.tests=backend/tests,frontend/test
sonar.test.inclusions=backend/tests/**/*.py,frontend/test/**/*.{js,jsx,ts,tsx}

sonar.python.coverage.reportPaths=backend/backend-coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.host.url=http://10.1.85.63:9000